apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hostly

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - zookeeper-deployment.yaml
  - kafka-deployment.yaml
  - mongodb-deployment.yaml
  - backend-deployment.yaml
  - agent-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: hostly
  app.kubernetes.io/part-of: hostly-platform

